config/routes.rb
Rails.application.routes.draw do
  root 'cars_details#index'
  get 'cars_details/index' => 'cars_details#index', as: :cars_details

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_details_controller.rb
class CarsDetailsController < ApplicationController

  	def index
	  	if params[:url].present?
		  	uri = URI.parse(params[:url])
		  	base_url = "#{uri.scheme}://#{uri.host}"
		  	complete_url = if uri.path.split("/").last.to_i == 0 then base_url+uri.path+"/"+Time.now.year.to_s else base_url+uri.path end
		  	redis_array = complete_url.split("/")
		  	redis_array.pop
		  	redis_key = redis_array.join("/")
  		  	@scrapped_urls = ["#{complete_url}"]
	  		@array = []
	  		if "#{uri.scheme}://#{uri.host}/#{uri.path.split("/").second}" == "http://uae.yallamotor.com/new-cars" and uri.path.split("/").third.present?
			  	if $redis.get("#{redis_key}").present?
			  		@redis_array = JSON.parse($redis.get("#{redis_key}"))
			  		@page = HTTParty.get(complete_url)
	  				page_parse = Nokogiri::HTML(@page)
				  	page_parse.css('#accordion2 .panel-default').each do |accordion|
					  	if accordion.css('a').first['href'] != "javascript:\;" 
				  	 		@scrapped_urls << if (base_url+accordion.css('a').first['href']).split("/").last.to_i == 0 then "#{base_url+accordion.css('a').first['href']}/#{Time.now.year}" else base_url+accordion.css('a').first['href'] end
						end
				 	end
				  	@array = @redis_array.select {|element| element.first.first == complete_url}
				  	@array << @redis_array.reject {|element| element.first.first == complete_url}
				  	@array.flatten!
			  	else	
			  		@page = HTTParty.get(complete_url)
		  			if @page.request.last_uri.to_s == complete_url
		  				page_parse = Nokogiri::HTML(@page)
					  	page_parse.css('#accordion2 .panel-default').map { |accordion| if accordion.css('a').first['href'] != "javascript:\;" then @scrapped_urls << base_url+accordion.css('a').first['href'] else nil end}
					  	@scrapped_urls.each_with_index do |url,url_index|
						  	if url_index > 0
							  	@page = HTTParty.get(url)
							  	page_parse = Nokogiri::HTML(@page)
						  	end
							content = page_parse.css('#collapse1')
							if content.present?
								@array << {"#{url}" => []}
						  		@array[url_index]["#{url}"] << Parallel.map(content.css('.new-car-name'), in_processes: 20) do |car,car_index|
									array_making(car,base_url)
								end
								@array[url_index]["#{url}"].flatten!
							end
						end
						$redis.set("#{redis_key}", @array.to_json)
					else
						@notice = "The provided url was redirected by app. Make sure your path is correct."
			  		end
				end
			else
				@notice = "This app is not made to scrape this url"
			end
	  	end
	end

private
	def array_making(car,base_url)
		car_hash = {"model" => car.text, "versions" => []}
  		car_details = HTTParty.get(base_url+car['href'].to_s)
  		car_details_page = Nokogiri::HTML(car_details)
		car_details_page.css('.prices-and-specs .new-cars-results-text h4').each_with_index do |car_details,details_index|
			car_version_hash = {"car_version" => car_details.css("a").text.gsub(/([\n])/, ''), "price" => car_details.css("span").text}
			car_hash["versions"] << car_version_hash
		end
		return car_hash
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_details_helper.rb
module CarsDetailsHelper
end

app/views/cars_details/index.html.erb
<div class="container">
<div style="background: white;padding: 0 20px;">
	
 <div class="row">
  <div class="col-md-12 text-center">
  <h1>Online Data Extractor</h1>
  </div>
  <div class="col-md-12 text-center" style="margin-top:20px; margin-bottom:20px;">
	<%= form_tag(cars_details_url, :method => :get, class: "form-inline", id: "url_form") do %>
		<div class="form-group">
		<span>
			<%= text_field_tag :url,nil,value: if params[:url].present? then params[:url] else nil end, class: 'form-control',required: true,placeholder: "Enter URL to scrap, e,g http://uae.yallamotor.com/new-cars/rolls-royce.", style: "width: 450px"%>
			</span>
			<button type="submit" class="btn btn-info">Extract</button>
	  	</div>
	<%end%>
  	</div>
  </div>
  <%if @array.present?%>
	 <div class="row">
	  <div class="col-md-12">
	   <table id="data-extractor-table" class="table table-striped table-bordered" cellspacing="0" width="100%">
	    <thead>
	     <tr>
	      <th>Type</th>
	      <th>Title</th>
	      <th>Price</th>
	     </tr>
	    </thead>
	    <tfoot>
	     <tr>
	      <th>Type</th>
	      <th>Title</th>
	      <th>Price</th>
	     </tr>
	    </tfoot>
	    <tbody>
		    <%@array.each_with_index do |arr,array_index|%>
		      	<%arr["#{@scrapped_urls[array_index]}"].each do |year_model|%>
	    			<tr>
			    	<td>Car Model</td>
		      		<td><%=year_model["model"]%></td>
			      	<td></td>
			      	</tr>
			    	<%year_model["versions"].each do |version|%>
					     <tr>
					      <td>Car Version</td>
					      <td><%= version["car_version"]%></td>
					      <td><%= version["price"]%></td>
					     </tr>
			     	<%end%>
		     	<%end%>
		    <%end%>
	    </tbody>
	   </table>
	  </div>
	 </div>
 <%elsif @notice.present?%>
 	<h1 class="text-center"><%=@notice%></h1>
 <%end%>
</div>
</div>

<script>
$(document).ready(function() {
    $('#data-extractor-table').dataTable({
    	"dom": 'T<"clear">lfrtip',
    	"aaSorting" : [],
    	"bSort" : false,
    	"tableTools": {
            "sSwfPath": "../assets/dataTables/swf/copy_csv_xls_pdf.swf"
        }
    });
    $("#url_form").validate({
		  rules: {
		    "url": {
		      required: true,
		      url: true,
		    }
		  },
		  messages:{
		    "url":{
		      required: "Please enter a url",
		      url: "Kindly enter a valid url to extract content"
		    }
		  }
		});
} );	
</script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineDataExtractor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background: #FAFAFA">

<%= yield %>

</body>
</html>